### PR TITLE
allowing all outputs to be saved in csv

### PR DESCRIPTION
**Pull request by bjoydeep**
This saves all the `history data that has been graphed `into `csv in the output dir`.

### CODE REVIEW

**Comment by ch-stark** [comment]
will test this new feature, we might consider a flag like: export csv, export png, for now I'll test to see if both png and csv will be exported

**Comment by ch-stark** [comment]
@bjoydeep is this correct testprocedure?

I checked out this branch:
git status
On branch adding-sizing-data
nothing to commit, working tree clean
[quickcluster@node-0 output]$ git remote -v
origin	https://github.com/bjoydeep/acm-inspector (fetch)
origin	https://github.com/bjoydeep/acm-inspector (push)

deleted output folder and started to inspector
I still see only png

**Comment by ch-stark** [comment]
tested also:
switching to main branch
git fetch origin pull/9/head:adding-sizing-data --force
run program, do not see CSV in output

**Comment by bjoydeep** [comment]
@ch-stark Thanks. Do you see any errors on the screen with `Failure in saving to CSV:` message?

**Comment by bjoydeep** [comment]
@ch-stark since you confirmed, this works, i am merging this on your behalf. Thanks for checking this out.

**Pull request merged**
